@startuml
left to right direction
rectangle Library{
(开户)
(借书)
(还书)
(查询图书)
(借阅历史)
(新增图书)
(修改图书)
(删除图书)
}
用户-->(开户)
用户-->(查询图书)
用户-->(借书)
用户-->(还书)
用户-->(借阅历史)
(借阅历史)<--管理员
(查询图书)<--管理员
(新增图书)<--管理员
(修改图书)<--管理员
(删除图书)<--管理员
@enduml